-- 001_initial_schema.sql — початкова схема БД Fire_depart (PostgreSQL)
-- PK: INTEGER GENERATED BY DEFAULT AS IDENTITY (дозволяє міграцію даних з явними id)
-- FK: з явними ON DELETE-політиками
-- Довідники сідаються внизу файлу.

BEGIN;

CREATE TABLE IF NOT EXISTS fire_stations (
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(120) NOT NULL UNIQUE,
    address VARCHAR(200) NOT NULL DEFAULT '',
    phone   VARCHAR(30)  NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS ranks (
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(60) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS employees (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    station_id INTEGER NOT NULL REFERENCES fire_stations(id) ON DELETE RESTRICT,
    rank_id    INTEGER          REFERENCES ranks(id)         ON DELETE SET NULL,
    full_name  VARCHAR(120) NOT NULL,
    phone      VARCHAR(30)  NOT NULL DEFAULT '',
    hired_at   DATE,
    is_active  BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT employees_name_not_empty CHECK (char_length(full_name) > 0)
);

CREATE TABLE IF NOT EXISTS shifts (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    station_id INTEGER  NOT NULL REFERENCES fire_stations(id) ON DELETE CASCADE,
    starts_at  TIMESTAMP NOT NULL,
    ends_at    TIMESTAMP NOT NULL,
    CONSTRAINT shifts_interval_valid CHECK (ends_at > starts_at)
);

CREATE TABLE IF NOT EXISTS shift_assignments (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shift_id    INTEGER NOT NULL REFERENCES shifts(id)   ON DELETE CASCADE,
    employee_id INTEGER NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    CONSTRAINT shift_assignments_unique UNIQUE (shift_id, employee_id)
);

CREATE TABLE IF NOT EXISTS vehicles (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    station_id    INTEGER NOT NULL REFERENCES fire_stations(id) ON DELETE RESTRICT,
    call_sign     VARCHAR(20) NOT NULL UNIQUE,
    vehicle_type  VARCHAR(60) NOT NULL DEFAULT '',
    status        VARCHAR(20) NOT NULL DEFAULT 'available'
                    CONSTRAINT vehicles_status_valid
                    CHECK (status IN ('available', 'on_call', 'maintenance', 'retired')),
    purchase_date DATE
);

CREATE TABLE IF NOT EXISTS incident_types (
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(80) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS incidents (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    station_id  INTEGER  NOT NULL REFERENCES fire_stations(id)  ON DELETE RESTRICT,
    type_id     INTEGER  NOT NULL REFERENCES incident_types(id) ON DELETE RESTRICT,
    address     VARCHAR(200) NOT NULL,
    description TEXT         NOT NULL DEFAULT '',
    received_at TIMESTAMP    NOT NULL DEFAULT NOW(),
    closed_at   TIMESTAMP,
    status      VARCHAR(20)  NOT NULL DEFAULT 'active'
                    CONSTRAINT incidents_status_valid
                    CHECK (status IN ('active', 'closed', 'cancelled')),
    CONSTRAINT incidents_closed_after_received CHECK (closed_at IS NULL OR closed_at >= received_at)
);

CREATE TABLE IF NOT EXISTS incident_vehicles (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_id   INTEGER  NOT NULL REFERENCES incidents(id) ON DELETE CASCADE,
    vehicle_id    INTEGER  NOT NULL REFERENCES vehicles(id)  ON DELETE RESTRICT,
    dispatched_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT incident_vehicles_unique UNIQUE (incident_id, vehicle_id)
);

CREATE TABLE IF NOT EXISTS incident_responders (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_id INTEGER NOT NULL REFERENCES incidents(id) ON DELETE CASCADE,
    employee_id INTEGER NOT NULL REFERENCES employees(id) ON DELETE RESTRICT,
    CONSTRAINT incident_responders_unique UNIQUE (incident_id, employee_id)
);

CREATE TABLE IF NOT EXISTS incident_reports (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_id INTEGER      NOT NULL UNIQUE REFERENCES incidents(id) ON DELETE CASCADE,
    summary     TEXT         NOT NULL DEFAULT '',
    damage_uah  NUMERIC(14,2) NOT NULL DEFAULT 0 CONSTRAINT incident_reports_damage_valid CHECK (damage_uah >= 0),
    casualties  INTEGER      NOT NULL DEFAULT 0 CONSTRAINT incident_reports_casualties_valid CHECK (casualties >= 0),
    created_at  TIMESTAMP    NOT NULL DEFAULT NOW()
);

-- Збережені позиції вузлів ERD-мапи (інтерактивний редактор схеми)
CREATE TABLE IF NOT EXISTS schema_layouts (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    view_name  VARCHAR(60) NOT NULL UNIQUE,
    positions  JSONB       NOT NULL,
    updated_at TIMESTAMP   NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_employees_station        ON employees(station_id);
CREATE INDEX IF NOT EXISTS idx_incidents_station_status ON incidents(station_id, status);
CREATE INDEX IF NOT EXISTS idx_incidents_received_at    ON incidents(received_at);
CREATE INDEX IF NOT EXISTS idx_vehicles_station_status   ON vehicles(station_id, status);

-- Сід довідників
INSERT INTO incident_types (title) VALUES
    ('Пожежа'),
    ('ДТП'),
    ('Задимлення'),
    ('Порятунок людей'),
    ('Інше')
ON CONFLICT (title) DO NOTHING;

INSERT INTO ranks (title) VALUES
    ('Рятувальник'),
    ('Старший рятувальник'),
    ('Командир відділення'),
    ('Начальник караулу')
ON CONFLICT (title) DO NOTHING;

COMMIT;
