package db

import (
	"context"
	"errors"
	"fmt"
	"regexp"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

var (
	identRe = regexp.MustCompile(`^[a-z_][a-z0-9_]{0,62}$`)
	typeRe  = regexp.MustCompile(`^(integer|bigint|smallint|text|boolean|date|timestamp|jsonb|varchar\(\d{1,4}\)|numeric\(\d{1,3},\d{1,3}\))$`)
)

var (
	ErrInvalidName = errors.New("некоректне ім'я: дозволені лише малі латинські літери, цифри і _, до 63 символів")
	ErrInvalidType = errors.New("некоректний тип колонки")
	ErrNoColumns   = errors.New("потрібна хоча б одна колонка")
)

// ColumnInput — колонка, яку створює користувач через UI.
type ColumnInput struct {
	Name     string
	Type     string
	Nullable bool
}

func validIdent(s string) bool {
	return identRe.MatchString(s)
}

func validateColumns(cols []ColumnInput) error {
	if len(cols) == 0 {
		return ErrNoColumns
	}
	seen := make(map[string]bool, len(cols))
	for _, c := range cols {
		if !validIdent(c.Name) || c.Name == "id" {
			return ErrInvalidName
		}
		if !typeRe.MatchString(c.Type) {
			return fmt.Errorf("%w: %s", ErrInvalidType, c.Type)
		}
		if seen[c.Name] {
			return fmt.Errorf("дублікат колонки: %s", c.Name)
		}
		seen[c.Name] = true
	}
	return nil
}

// CreateTable створює таблицю з автогенерованим PK id.
func CreateTable(ctx context.Context, pool *pgxpool.Pool, name string, cols []ColumnInput) error {
	if !validIdent(name) {
		return ErrInvalidName
	}
	if err := validateColumns(cols); err != nil {
		return err
	}
	ddl := fmt.Sprintf("CREATE TABLE %s (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", name)
	for _, c := range cols {
		ddl += fmt.Sprintf(", %s %s", c.Name, c.Type)
		if !c.Nullable {
			ddl += " NOT NULL"
		}
	}
	ddl += ")"
	_, err := pool.Exec(ctx, ddl)
	return err
}

// DropTable видаляє таблицю (без CASCADE — залежні FK не дадуть видалити навмання).
func DropTable(ctx context.Context, pool *pgxpool.Pool, name string) error {
	if _, ok := tableDef(name); !ok {
		return ErrUnknownTable
	}
	_, err := pool.Exec(ctx, fmt.Sprintf("DROP TABLE %s", name))
	return err
}

// AddColumn додає колонку до таблиці.
func AddColumn(ctx context.Context, pool *pgxpool.Pool, table, colName, colType string, nullable bool) error {
	def, ok := tableDef(table)
	if !ok {
		return ErrUnknownTable
	}
	if !validIdent(colName) || colName == "id" {
		return ErrInvalidName
	}
	if !typeRe.MatchString(colType) {
		return fmt.Errorf("%w: %s", ErrInvalidType, colType)
	}
	for _, c := range def.Columns {
		if c.Name == colName {
			return fmt.Errorf("колонка %s уже існує", colName)
		}
	}
	null := ""
	if !nullable {
		null = " NOT NULL"
	}
	_, err := pool.Exec(ctx, fmt.Sprintf("ALTER TABLE %s ADD COLUMN %s %s%s", table, colName, colType, null))
	return err
}

// DropColumn видаляє колонку (крім первинного ключа).
func DropColumn(ctx context.Context, pool *pgxpool.Pool, table, colName string) error {
	def, ok := tableDef(table)
	if !ok {
		return ErrUnknownTable
	}
	found := false
	for _, c := range def.Columns {
		if c.Name == colName {
			if c.Primary {
				return errors.New("не можна видаляти первинний ключ")
			}
			found = true
		}
	}
	if !found {
		return pgx.ErrNoRows
	}
	_, err := pool.Exec(ctx, fmt.Sprintf("ALTER TABLE %s DROP COLUMN %s", table, colName))
	return err
}
