// Package db містить канонічну схему PostgreSQL для Fire_depart.
// Назви колонок (hired_at, shift_no, dispatch_id, damage_uah) — єдине джерело
// правди, щоб не повторити розсинхрон meta.go зі старого проєкту.
package db

// schema — DDL у діалекті PostgreSQL.
const schema = `
CREATE TABLE IF NOT EXISTS firefighters (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(120) NOT NULL,
    rank      VARCHAR(60)  NOT NULL DEFAULT '',
    hired_at  TIMESTAMP,
    is_active BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS shifts (
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shift_no INTEGER     NOT NULL,
    label    VARCHAR(40) NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS calls (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address     VARCHAR(200) NOT NULL,
    received_at TIMESTAMP    NOT NULL DEFAULT NOW(),
    closed_at   TIMESTAMP,
    shift_id    INTEGER REFERENCES shifts(id),
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS damages (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dispatch_id INTEGER       NOT NULL REFERENCES calls(id),
    description TEXT          NOT NULL DEFAULT '',
    damage_uah  NUMERIC(14,2) NOT NULL DEFAULT 0
);
`

// Schema повертає DDL-скрипт створення всіх таблиць.
func Schema() string {
	return schema
}
